In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
%matplotlib inline
print('Done!')

Done!


In [2]:
train_data = pd.read_csv('C:\\Users\\Auditor\\Desktop\\Victor\\New folder\\Data Science\\Projects\Multi-Class Prediction of Cirrhosis Outcomes\\train.csv')

In [3]:
test_data = pd.read_csv('C:\\Users\\Auditor\\Desktop\\Victor\\New folder\\Data Science\\Projects\Multi-Class Prediction of Cirrhosis Outcomes\\test.csv')

In [4]:
train_data

id  N_Days             Drug    Age Sex Ascites Hepatomegaly Spiders  \
0        0     999  D-penicillamine  21532   M       N            N       N   
1        1    2574          Placebo  19237   F       N            N       N   
2        2    3428          Placebo  13727   F       N            Y       Y   
3        3    2576          Placebo  18460   F       N            N       N   
4        4     788          Placebo  16658   F       N            Y       N   
...    ...     ...              ...    ...  ..     ...          ...     ...   
7900  7900    1166  D-penicillamine  16839   F       N            N       N   
7901  7901    1492          Placebo  17031   F       N            Y       N   
7902  7902    1576  D-penicillamine  25873   F       N            N       Y   
7903  7903    3584  D-penicillamine  22960   M       N            Y       N   
7904  7904    1978  D-penicillamine  19237   F       N            N       N   

     Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0        N        2.3        316.0     3.35   172.0    1601.0  179.80   
1        N        0.9        364.0     3.54    63.0    1440.0  134.85   
2        Y        3.3        299.0     3.55   131.0    1029.0  119.35   
3        N        0.6        256.0     3.50    58.0    1653.0   71.30   
4        N        1.1        346.0     3.65    63.0    1181.0  125.55   
...    ...        ...          ...      ...     ...       ...     ...   
7900     N        0.8        309.0     3.56    38.0    1629.0   79.05   
7901     N        0.9        260.0     3.43    62.0    1440.0  142.00   
7902     S        2.0        225.0     3.19    51.0     933.0   69.75   
7903     N        0.7        248.0     2.75    32.0    1003.0   57.35   
7904     N        0.7        256.0     3.23    22.0     645.0   74.40   

      Tryglicerides  Platelets  Prothrombin  Stage Status  
0              63.0      394.0          9.7    3.0      D  
1              88.0      361.0         11.0    3.0      C  
2              50.0      199.0         11.7    4.0      D  
3              96.0      269.0         10.7    3.0      C  
4              96.0      298.0         10.6    4.0      C  
...             ...        ...          ...    ...    ...  
7900          224.0      344.0          9.9    2.0      C  
7901           78.0      277.0         10.0    4.0      C  
7902           62.0      200.0         12.7    2.0      D  
7903          118.0      221.0         10.6    4.0      D  
7904           85.0      336.0         10.3    3.0      C  

[7905 rows x 20 columns]

In [5]:
test_data

id  N_Days             Drug    Age Sex Ascites Hepatomegaly Spiders  \
0      7905    3839  D-penicillamine  19724   F       N            Y       N   
1      7906    2468  D-penicillamine  14975   F       N            N       N   
2      7907      51          Placebo  13149   F       N            Y       N   
3      7908    2330  D-penicillamine  20510   F       N            N       N   
4      7909    1615  D-penicillamine  21904   F       N            Y       N   
...     ...     ...              ...    ...  ..     ...          ...     ...   
5266  13171    2870          Placebo  12279   F       N            N       N   
5267  13172    1770          Placebo  24803   F       N            N       N   
5268  13173    3707  D-penicillamine  16990   F       N            Y       N   
5269  13174    1216          Placebo  11773   F       N            N       N   
5270  13175    2272  D-penicillamine  21600   F       N            N       N   

     Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0        N        1.2        546.0     3.37    65.0    1636.0  151.90   
1        N        1.1        660.0     4.22    94.0    1257.0  151.90   
2        Y        2.0        151.0     2.96    46.0     961.0   69.75   
3        N        0.6        293.0     3.85    40.0     554.0  125.55   
4        N        1.4        277.0     2.97   121.0    1110.0  125.00   
...    ...        ...          ...      ...     ...       ...     ...   
5266     N        1.3        302.0     3.43    75.0    1345.0  145.00   
5267     N        0.5        219.0     4.09   121.0     663.0   79.05   
5268     N        0.8        315.0     4.09    13.0    1637.0  170.50   
5269     N        0.7        329.0     3.80    52.0     678.0   57.00   
5270     N        2.0        232.0     3.42    18.0    1636.0  170.50   

      Tryglicerides  Platelets  Prothrombin  Stage  
0              90.0      430.0         10.6    2.0  
1             155.0      227.0         10.0    2.0  
2             101.0      213.0         13.0    4.0  
3              56.0      270.0         10.6    2.0  
4             126.0      221.0          9.8    1.0  
...             ...        ...          ...    ...  
5266           44.0      181.0         10.6    3.0  
5267           94.0      311.0          9.7    3.0  
5268           70.0      426.0         10.9    3.0  
5269          126.0      306.0         10.2    1.0  
5270           83.0      213.0         13.6    2.0  

[5271 rows x 19 columns]

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7905 entries, 0 to 7904
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             7905 non-null   int64  
 1   N_Days         7905 non-null   int64  
 2   Drug           7905 non-null   object 
 3   Age            7905 non-null   int64  
 4   Sex            7905 non-null   object 
 5   Ascites        7905 non-null   object 
 6   Hepatomegaly   7905 non-null   object 
 7   Spiders        7905 non-null   object 
 8   Edema          7905 non-null   object 
 9   Bilirubin      7905 non-null   float64
 10  Cholesterol    7905 non-null   float64
 11  Albumin        7905 non-null   float64
 12  Copper         7905 non-null   float64
 13  Alk_Phos       7905 non-null   float64
 14  SGOT           7905 non-null   float64
 15  Tryglicerides  7905 non-null   float64
 16  Platelets      7905 non-null   float64
 17  Prothrombin    7905 non-null   float64
 18  Stage   

In [7]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5271 entries, 0 to 5270
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             5271 non-null   int64  
 1   N_Days         5271 non-null   int64  
 2   Drug           5271 non-null   object 
 3   Age            5271 non-null   int64  
 4   Sex            5271 non-null   object 
 5   Ascites        5271 non-null   object 
 6   Hepatomegaly   5271 non-null   object 
 7   Spiders        5271 non-null   object 
 8   Edema          5271 non-null   object 
 9   Bilirubin      5271 non-null   float64
 10  Cholesterol    5271 non-null   float64
 11  Albumin        5271 non-null   float64
 12  Copper         5271 non-null   float64
 13  Alk_Phos       5271 non-null   float64
 14  SGOT           5271 non-null   float64
 15  Tryglicerides  5271 non-null   float64
 16  Platelets      5271 non-null   float64
 17  Prothrombin    5271 non-null   float64
 18  Stage   

In [8]:

def count_object_columns(df):
    """
    Count the occurrences of each unique value in object-type columns.

    Parameters:
    - df: Pandas DataFrame.

    Returns:
    - Dictionary containing column names as keys and their value counts as values.
    """
    object_columns = df.select_dtypes(include='object').columns
    counts = {}

    for column in object_columns:
        counts[column] = df[column].value_counts()

    return counts

# Example usage:
# Assuming 'train_data' is your actual DataFrame
result = count_object_columns(train_data)

# Display the counts for each object-type column
for column, count in result.items():
    print(f'Column: {column}\n{count}\n')

Column: Drug
Placebo            4010
D-penicillamine    3895
Name: Drug, dtype: int64

Column: Sex
F    7336
M     569
Name: Sex, dtype: int64

Column: Ascites
N    7525
Y     380
Name: Ascites, dtype: int64

Column: Hepatomegaly
Y    4042
N    3863
Name: Hepatomegaly, dtype: int64

Column: Spiders
N    5966
Y    1939
Name: Spiders, dtype: int64

Column: Edema
N    7161
S     399
Y     345
Name: Edema, dtype: int64

Column: Status
C     4965
D     2665
CL     275
Name: Status, dtype: int64



In [9]:
# Assuming 'test_data' is your actual DataFrame
result2 = count_object_columns(test_data)

# Display the counts for each object-type column
for column, count in result2.items():
    print(f'Column: {column}\n{count}\n')

Column: Drug
Placebo            2694
D-penicillamine    2577
Name: Drug, dtype: int64

Column: Sex
F    4877
M     394
Name: Sex, dtype: int64

Column: Ascites
N    5027
Y     244
Name: Ascites, dtype: int64

Column: Hepatomegaly
Y    2730
N    2541
Name: Hepatomegaly, dtype: int64

Column: Spiders
N    3972
Y    1299
Name: Spiders, dtype: int64

Column: Edema
N    4786
S     262
Y     223
Name: Edema, dtype: int64



In [10]:
# Print or use the list of columns as needed
print(train_data.columns.tolist())

['id', 'N_Days', 'Drug', 'Age', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage', 'Status']


In [11]:
#all columns are necessary

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

class GetDummies(BaseEstimator, TransformerMixin):
    
    def __init__(self, column_names):
        self.column_names = column_names

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        columns = X[self.column_names]  # Extract the specified columns

        # Apply one-hot encoding to each specified column
        dummies_list = [pd.get_dummies(columns[col], prefix=col) for col in self.column_names]

        # Concatenate one-hot encoded columns with the original DataFrame and delete dummied column
        X_encoded = pd.concat([X] + dummies_list, axis=1).drop(self.column_names, axis=1)

        return X_encoded

In [13]:
pipeline = Pipeline([
    ('get_dummies', GetDummies(column_names=['Drug', 'Sex','Ascites','Hepatomegaly','Spiders','Edema']))
])

In [14]:
train_data = pipeline.fit_transform(train_data)

In [15]:
train_data

id  N_Days    Age  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos  \
0        0     999  21532        2.3        316.0     3.35   172.0    1601.0   
1        1    2574  19237        0.9        364.0     3.54    63.0    1440.0   
2        2    3428  13727        3.3        299.0     3.55   131.0    1029.0   
3        3    2576  18460        0.6        256.0     3.50    58.0    1653.0   
4        4     788  16658        1.1        346.0     3.65    63.0    1181.0   
...    ...     ...    ...        ...          ...      ...     ...       ...   
7900  7900    1166  16839        0.8        309.0     3.56    38.0    1629.0   
7901  7901    1492  17031        0.9        260.0     3.43    62.0    1440.0   
7902  7902    1576  25873        2.0        225.0     3.19    51.0     933.0   
7903  7903    3584  22960        0.7        248.0     2.75    32.0    1003.0   
7904  7904    1978  19237        0.7        256.0     3.23    22.0     645.0   

        SGOT  Tryglicerides  ...  Sex_M  Ascites_N  Ascites_Y Hepatomegaly_N  \
0     179.80           63.0  ...      1          1          0              1   
1     134.85           88.0  ...      0          1          0              1   
2     119.35           50.0  ...      0          1          0              0   
3      71.30           96.0  ...      0          1          0              1   
4     125.55           96.0  ...      0          1          0              0   
...      ...            ...  ...    ...        ...        ...            ...   
7900   79.05          224.0  ...      0          1          0              1   
7901  142.00           78.0  ...      0          1          0              0   
7902   69.75           62.0  ...      0          1          0              1   
7903   57.35          118.0  ...      1          1          0              0   
7904   74.40           85.0  ...      0          1          0              1   

      Hepatomegaly_Y  Spiders_N  Spiders_Y  Edema_N  Edema_S  Edema_Y  
0                  0          1          0        1        0        0  
1                  0          1          0        1        0        0  
2                  1          0          1        0        0        1  
3                  0          1          0        1        0        0  
4                  1          1          0        1        0        0  
...              ...        ...        ...      ...      ...      ...  
7900               0          1          0        1        0        0  
7901               1          1          0        1        0        0  
7902               0          0          1        0        1        0  
7903               1          1          0        1        0        0  
7904               0          1          0        1        0        0  

[7905 rows x 27 columns]

In [16]:
# Print or use the list of columns as needed
print(train_data.columns.tolist())

['id', 'N_Days', 'Age', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage', 'Status', 'Drug_D-penicillamine', 'Drug_Placebo', 'Sex_F', 'Sex_M', 'Ascites_N', 'Ascites_Y', 'Hepatomegaly_N', 'Hepatomegaly_Y', 'Spiders_N', 'Spiders_Y', 'Edema_N', 'Edema_S', 'Edema_Y']


In [17]:
train_data = train_data[['id', 'N_Days', 'Age', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage', 'Drug_D-penicillamine', 'Drug_Placebo', 'Sex_F', 'Sex_M', 'Ascites_N', 'Ascites_Y', 'Hepatomegaly_N', 'Hepatomegaly_Y', 'Spiders_N', 'Spiders_Y', 'Edema_N', 'Edema_S', 'Edema_Y', 'Status']
]

In [18]:
train_data

id  N_Days    Age  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos  \
0        0     999  21532        2.3        316.0     3.35   172.0    1601.0   
1        1    2574  19237        0.9        364.0     3.54    63.0    1440.0   
2        2    3428  13727        3.3        299.0     3.55   131.0    1029.0   
3        3    2576  18460        0.6        256.0     3.50    58.0    1653.0   
4        4     788  16658        1.1        346.0     3.65    63.0    1181.0   
...    ...     ...    ...        ...          ...      ...     ...       ...   
7900  7900    1166  16839        0.8        309.0     3.56    38.0    1629.0   
7901  7901    1492  17031        0.9        260.0     3.43    62.0    1440.0   
7902  7902    1576  25873        2.0        225.0     3.19    51.0     933.0   
7903  7903    3584  22960        0.7        248.0     2.75    32.0    1003.0   
7904  7904    1978  19237        0.7        256.0     3.23    22.0     645.0   

        SGOT  Tryglicerides  ...  Ascites_N  Ascites_Y  Hepatomegaly_N  \
0     179.80           63.0  ...          1          0               1   
1     134.85           88.0  ...          1          0               1   
2     119.35           50.0  ...          1          0               0   
3      71.30           96.0  ...          1          0               1   
4     125.55           96.0  ...          1          0               0   
...      ...            ...  ...        ...        ...             ...   
7900   79.05          224.0  ...          1          0               1   
7901  142.00           78.0  ...          1          0               0   
7902   69.75           62.0  ...          1          0               1   
7903   57.35          118.0  ...          1          0               0   
7904   74.40           85.0  ...          1          0               1   

      Hepatomegaly_Y  Spiders_N  Spiders_Y  Edema_N  Edema_S  Edema_Y  Status  
0                  0          1          0        1        0        0       D  
1                  0          1          0        1        0        0       C  
2                  1          0          1        0        0        1       D  
3                  0          1          0        1        0        0       C  
4                  1          1          0        1        0        0       C  
...              ...        ...        ...      ...      ...      ...     ...  
7900               0          1          0        1        0        0       C  
7901               1          1          0        1        0        0       C  
7902               0          0          1        0        1        0       D  
7903               1          1          0        1        0        0       D  
7904               0          1          0        1        0        0       C  

[7905 rows x 27 columns]

In [19]:
pipeline2 = Pipeline([
    ('get_dummies', GetDummies(column_names=['Drug', 'Sex','Ascites','Hepatomegaly','Spiders','Edema',]))
])

In [20]:
test_data = pipeline2.fit_transform(test_data)

In [21]:
test_data

id  N_Days    Age  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos  \
0      7905    3839  19724        1.2        546.0     3.37    65.0    1636.0   
1      7906    2468  14975        1.1        660.0     4.22    94.0    1257.0   
2      7907      51  13149        2.0        151.0     2.96    46.0     961.0   
3      7908    2330  20510        0.6        293.0     3.85    40.0     554.0   
4      7909    1615  21904        1.4        277.0     2.97   121.0    1110.0   
...     ...     ...    ...        ...          ...      ...     ...       ...   
5266  13171    2870  12279        1.3        302.0     3.43    75.0    1345.0   
5267  13172    1770  24803        0.5        219.0     4.09   121.0     663.0   
5268  13173    3707  16990        0.8        315.0     4.09    13.0    1637.0   
5269  13174    1216  11773        0.7        329.0     3.80    52.0     678.0   
5270  13175    2272  21600        2.0        232.0     3.42    18.0    1636.0   

        SGOT  Tryglicerides  ...  Sex_M  Ascites_N  Ascites_Y  Hepatomegaly_N  \
0     151.90           90.0  ...      0          1          0               0   
1     151.90          155.0  ...      0          1          0               1   
2      69.75          101.0  ...      0          1          0               0   
3     125.55           56.0  ...      0          1          0               1   
4     125.00          126.0  ...      0          1          0               0   
...      ...            ...  ...    ...        ...        ...             ...   
5266  145.00           44.0  ...      0          1          0               1   
5267   79.05           94.0  ...      0          1          0               1   
5268  170.50           70.0  ...      0          1          0               0   
5269   57.00          126.0  ...      0          1          0               1   
5270  170.50           83.0  ...      0          1          0               1   

      Hepatomegaly_Y  Spiders_N  Spiders_Y  Edema_N  Edema_S  Edema_Y  
0                  1          1          0        1        0        0  
1                  0          1          0        1        0        0  
2                  1          1          0        0        0        1  
3                  0          1          0        1        0        0  
4                  1          1          0        1        0        0  
...              ...        ...        ...      ...      ...      ...  
5266               0          1          0        1        0        0  
5267               0          1          0        1        0        0  
5268               1          1          0        1        0        0  
5269               0          1          0        1        0        0  
5270               0          1          0        1        0        0  

[5271 rows x 26 columns]

In [22]:
from sklearn.preprocessing import StandardScaler

X = train_data.drop(['Status'], axis=1)
y = train_data['Status']

scaler = StandardScaler()
X_data = scaler.fit_transform(X)
y_data = y.to_numpy()

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import log_loss



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a pipeline with a RandomForestClassifier
model = Pipeline([
    ('scaler', StandardScaler()),  # Optional: Standardize your features
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict the target labels and probabilities for the test set
predicted_labels = model.predict(X_test)
predicted_probabilities = model.predict_proba(X_test)

# Calculate log loss
logloss = log_loss(y_test, predicted_probabilities)

# Display log loss
print(f"Log Loss: {logloss}")

# Display classification report
from sklearn.metrics import classification_report
print("Classification Report:")
print(classification_report(y_test, predicted_labels))


Log Loss: 0.606401828967551
Classification Report:
              precision    recall  f1-score   support

           C       0.83      0.93      0.88       966
          CL       0.67      0.12      0.20        52
           D       0.85      0.73      0.78       563

    accuracy                           0.83      1581
   macro avg       0.78      0.59      0.62      1581
weighted avg       0.83      0.83      0.82      1581



In [24]:
#prediction_ll = model.predict(test_data)

In [25]:
#prediction_ll

In [26]:
# Display the predicted labels
print("Predicted Labels:")
print(predicted_labels)

# Display the predicted probabilities for the first few samples
print("\nPredicted Probabilities:")
print(predicted_probabilities[:5])  # Displaying the first 5 rows for illustration purposes


Predicted Labels:
['C' 'D' 'C' ... 'D' 'C' 'C']

Predicted Probabilities:
[[0.93 0.01 0.06]
 [0.42 0.06 0.52]
 [0.81 0.05 0.14]
 [0.9  0.   0.1 ]
 [0.89 0.03 0.08]]


In [28]:
len(predicted_probabilities)

1581

In [33]:
predicted_probabilities

array([[0.63, 0.05, 0.32],
       [0.74, 0.1 , 0.16],
       [0.2 , 0.04, 0.76],
       ...,
       [0.84, 0.04, 0.12],
       [0.88, 0.03, 0.09],
       [0.47, 0.06, 0.47]])

In [34]:
Results = pd.DataFrame(test_data['id'])
Results[['Status_C', 'Status_CL', 'Status_D']] = predicted_probabilities
Results.to_csv('Downloads/Cirrhosisll.csv', index =False)

In [35]:
Results

id  Status_C  Status_CL  Status_D
0      7905      0.63       0.05      0.32
1      7906      0.74       0.10      0.16
2      7907      0.20       0.04      0.76
3      7908      0.82       0.01      0.17
4      7909      0.67       0.10      0.23
...     ...       ...        ...       ...
5266  13171      0.74       0.12      0.14
5267  13172      0.79       0.03      0.18
5268  13173      0.84       0.04      0.12
5269  13174      0.88       0.03      0.09
5270  13175      0.47       0.06      0.47

[5271 rows x 4 columns]